"""
C-mode prompt templates for WasmDiscrepancyRepair instrumentation.

This module holds the C-language variants of prompts that the default C++
pipeline uses. They are selected when ``metadata.json`` sets
``project_language`` to ``"C"`` in its ``Test Case Failure Info`` block.

Design notes:
- All printing uses ``fprintf(FILE*, ...)`` with C-style format specifiers,
  not ``std::cout``/``operator<<``.
- Primitive integers are cast to ``long long`` / ``unsigned long long`` and
  printed with ``%lld`` / ``%llu`` to avoid format-specifier mismatches
  across architectures.
- Strings (``char*``) use ``%.200s`` for length capping, with an explicit
  ``NULL`` guard.
- Pointers to other types use ``%p``.
- User-defined struct/union/enum types are printed via
  ``print_<name>(FILE*, const struct <name>*)`` helpers generated by
  ``CPrintInstrumentor``.
"""

# ---------------------------------------------------------------------------
# Function-repair prompt (C variant of LLMInstrumentor.py:978-1033)
# ---------------------------------------------------------------------------
# This is an f-string template that the caller fills with `func_name`,
# `relevant_errors`, `original_func_text`, and `previous_attempt`. Keep the
# named placeholders identical to the C++ version so the caller can swap
# between them by flag without changing argument wiring.

C_REPAIR_PROMPT_TEMPLATE = """Fix the compilation errors in this instrumented C function.

FUNCTION: {func_name}

COMPILATION ERRORS:
```
{relevant_errors}
```

ORIGINAL FUNCTION (before instrumentation — compiles fine):
```c
{original_func_text}
```

CURRENT ATTEMPT (has compilation errors):
```c
{previous_attempt}
```

INSTRUCTIONS:
1. Read the compilation errors carefully and fix exactly what they say.
2. Preserve all instrumentation markers (@@INST_START_/@@INST_END_ and @@FUNC_ID_...@@).
3. Preserve the original program logic — only fix the instrumentation code.
4. CUSTOM TYPES: ``print_<TypeName>(FILE *out, const struct <TypeName> *obj)`` helpers have been pre-generated for user-defined types. Call them like ``print_interval(stderr, &obj);``.
5. FORMAT SPECIFIERS (CRITICAL): fprintf is NOT type-safe. Mismatched specifiers silently corrupt output. Use:
   - Signed integers (char, short, int, long, int8_t..int64_t): cast to ``(long long)`` and print with ``%lld``.
   - Unsigned integers (unsigned, size_t, uint8_t..uint64_t): cast to ``(unsigned long long)`` and print with ``%llu``.
   - Floats/doubles: cast to ``(double)`` and print with ``%g``.
   - char*/const char*: use ``%.200s`` with an explicit NULL guard:
     ```c
     fprintf(stderr, "s=%.200s\\n", p ? p : "(null)");
     ```
   - Other pointers (int*, struct Foo*): print address only with ``%p``:
     ```c
     fprintf(stderr, "p=%p\\n", (void*)p);
     ```
   - Enum values: cast to ``(int)`` and print with ``%d``.
   - For a user-defined struct, call its generated ``print_<name>`` helper:
     ```c
     fprintf(stderr, "obj=");
     print_interval(stderr, &obj);
     fprintf(stderr, "\\n");
     ```
6. Do NOT dereference a pointer you have not null-checked.
7. If a specific variable causes a compilation error and you cannot figure out how to print it, commenting out that particular fprintf line is also a valid fix. For example:
   ``// fprintf(stderr, "x = %lld\\n", (long long)x);  // commented out: unprintable type``
8. Return ONLY the fixed function with NO explanation, NO markdown formatting, NO additional text.

CRITICAL: The code MUST compile with a C compiler."""


# ---------------------------------------------------------------------------
# Fallback instrumentation prompt (C variant of
# diff_trace_analysis.py:2001-2030)
# ---------------------------------------------------------------------------
# The caller formats this with ``original_func_text`` and the chosen output
# stream (``stderr`` or ``stdout``). Keep the marker line format identical
# to the C++ version so downstream parsers see the same bytes.

def build_c_fallback_instrumentation_prompt(original_func_text: str,
                                            output_stream: str) -> str:
    """Build the C-mode fallback prompt for failed function instrumentation.

    Args:
        original_func_text: Function body with TODO comments containing
            marker strings.
        output_stream: ``"stderr"`` or ``"stdout"``.
    """
    return f"""The instrumentation of the following C function failed to compile after multiple attempts.
As a fallback, produce a MINIMAL version that ONLY prints entry and exit markers at the very beginning and end of the function body.

ORIGINAL FUNCTION (with TODO comments containing the marker strings):
```c
{original_func_text}
```

REQUIREMENTS:
1. Extract the @@INST_START_...@@ and @@INST_END_...@@ marker strings from the TODO comments.
2. At the BEGINNING of the function body (right after the opening '{{'), add an entry block for each TODO ENTRY marker:
     fprintf({output_stream}, "@@INST_START_<marker>@@\\n");
     fprintf({output_stream}, "@@FUNC_ID_<funcname>_<hash>@@\\n");
     fprintf({output_stream}, "+++Below are Input+++\\n");
     fprintf({output_stream}, "Fail to print vars\\n");
     fprintf({output_stream}, "@@INST_END_<marker>@@\\n");
   Copy the FUNC_ID line exactly from the TODO comment.
3. At the END of the function body (right before the closing '}}'), add an exit block for each TODO EXIT marker:
     fprintf({output_stream}, "@@INST_START_<marker>@@\\n");
     fprintf({output_stream}, "@@FUNC_ID_<funcname>_<hash>@@\\n");
     fprintf({output_stream}, "---Below are Outputs---\\n");
     fprintf({output_stream}, "Fail to print vars\\n");
     fprintf({output_stream}, "@@INST_END_<marker>@@\\n");
   IMPORTANT: @@FUNC_ID_...@@ MUST be INSIDE the @@INST_START_...@@/@@INST_END_...@@ block.
4. REMOVE all the /*[Instrumented]...TODO...*/ comment blocks.
5. Do NOT print any variables — just the marker pairs.
6. Use fprintf({output_stream}, ...) for ALL printing statements. Do NOT use std::cout, std::cerr, or iostream.
7. Include <stdio.h> if not already included.
8. Do NOT modify any other code in the function.
9. The code MUST compile with BOTH gcc (native) and emcc (wasm).
10. Return ONLY the modified function with NO explanation, NO markdown formatting, NO additional text."""


# ---------------------------------------------------------------------------
# Print-helper prompts (C equivalents of the operator<< LLM prompts in
# diff_trace_analysis.py:228-234, 443-465, 510-525)
# ---------------------------------------------------------------------------

C_PRINT_HELPER_SYSTEM_PROMPT = (
    "You are an expert in C programming. Your task is to write "
    "``print_<TypeName>(FILE *out, const <Type> *obj)`` helper functions "
    "that serialize a C struct/union/enum to a FILE* stream using fprintf. "
    "The function must be declared as ``static inline`` so it can safely "
    "appear in a header file. Return ONLY the requested C code with NO "
    "explanation, NO markdown formatting, NO additional text."
)


def build_c_print_helper_repair_prompt(qname: str,
                                       file_basename: str,
                                       error_snippet: str,
                                       type_body: str,
                                       old_code: str) -> str:
    """Build a repair prompt for a failed print helper compilation."""
    return (
        f"Fix the compilation errors in this print helper function "
        f"for type `{qname}` in {file_basename}.\n\n"
        f"COMPILATION ERRORS (relevant to this file):\n"
        f"```\n{error_snippet}\n```\n\n"
        f"TYPE DEFINITION:\n```c\n{type_body}\n```\n\n"
        f"YOUR PREVIOUS ATTEMPT (has compilation error):\n"
        f"```c\n{old_code}\n```\n\n"
        f"IMPORTANT NOTES:\n"
        f"- The function MUST be declared ``static inline`` so multiple "
        f"translation units can include it without ODR violation.\n"
        f"- The function signature MUST be "
        f"``static inline void print_{qname.replace('::', '_')}(FILE *out, "
        f"const struct {qname} *obj)`` for structs/unions, or "
        f"``static inline void print_{qname.replace('::', '_')}(FILE *out, "
        f"enum {qname} val)`` for enums.\n"
        f"- Use fprintf with proper format specifiers:\n"
        f"  * Signed integers → cast to (long long), use %lld\n"
        f"  * Unsigned integers → cast to (unsigned long long), use %llu\n"
        f"  * Floats/doubles → cast to (double), use %g\n"
        f"  * char* → use %.200s with NULL guard\n"
        f"  * Other pointers → use %p\n"
        f"  * Nested struct member → call its print_<name> helper recursively\n"
        f"- Null-check the top-level ``obj`` pointer before dereferencing it.\n"
        f"- If a member is not printable, print ``\"<name>=(non-printable)\"``.\n\n"
        f"CRITICAL: The code MUST compile with a C compiler. Read the error "
        f"messages carefully and fix exactly what they say.\n\n"
        f"Return ONLY the corrected print helper function definition "
        f"with NO explanation, NO markdown formatting, NO additional text."
    )


def build_c_print_helper_fallback_prompt(qname: str, type_body: str,
                                         kind: str) -> str:
    """Build a trivial-fallback prompt for a print helper that cannot be
    repaired.

    The trivial fallback prints only the type name as a placeholder, so the
    function compiles and downstream code that calls it still works.
    """
    fname = f"print_{qname.replace('::', '_')}"
    if kind == "enum":
        sig = f"static inline void {fname}(FILE *out, enum {qname} val)"
        body = f'    (void)val;\n    fprintf(out, "{qname}{{}}");'
    else:
        # struct/union
        prefix = "union" if kind == "union" else "struct"
        sig = (f"static inline void {fname}(FILE *out, "
               f"const {prefix} {qname} *obj)")
        body = (f'    (void)obj;\n    fprintf(out, "{qname}{{}}");')
    example = f"{sig} {{\n{body}\n}}"

    return (
        f"The previous print helper for type `{qname}` failed to "
        f"compile after multiple attempts. Write a trivial "
        f"print helper that simply prints the type name "
        f"\"{qname}\" as a literal placeholder.\n\n"
        f"TYPE DEFINITION:\n```c\n{type_body}\n```\n\n"
        f"The function MUST be ``static inline`` and use fprintf to write "
        f"to the FILE* parameter. For example:\n"
        f"```c\n{example}\n```\n\n"
        f"Return ONLY the print helper function definition "
        f"with NO explanation, NO markdown formatting, NO "
        f"additional text."
    )
